/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

/**
 *
 * @author Nhi
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageStudent = new javax.swing.JButton();
        btnManageSchedule = new javax.swing.JButton();
        btnManageStudentScore = new javax.swing.JButton();
        btnManageClass = new javax.swing.JButton();
        btnReexam = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnListReexam = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnManageStudent.setText("Quan Ly Sinh Vien");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnManageSchedule.setText("Quan Ly TKB");
        btnManageSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageScheduleActionPerformed(evt);
            }
        });

        btnManageStudentScore.setText("Quan Ly Diem");
        btnManageStudentScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentScoreActionPerformed(evt);
            }
        });

        btnManageClass.setText("Quan Ly Mon Hoc");
        btnManageClass.setActionCommand("Tao Dot Phuc khao");
        btnManageClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClassActionPerformed(evt);
            }
        });

        btnReexam.setText("Tao Phuc Khao");
        btnReexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReexamActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Doi mat khau");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnLogout.setText("Dang Xuat");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnListReexam.setText("Danh Sach Phuc Khao");
        btnListReexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListReexamActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        label.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListReexam, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReexam, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudentScore, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(18, 18, 18)
                .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageSchedule)
                .addGap(18, 18, 18)
                .addComponent(btnManageClass)
                .addGap(18, 18, 18)
                .addComponent(btnManageStudentScore)
                .addGap(18, 18, 18)
                .addComponent(btnReexam)
                .addGap(18, 18, 18)
                .addComponent(btnListReexam)
                .addGap(18, 18, 18)
                .addComponent(btnChangePassword)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
   ManageStudent student = new ManageStudent();
        student .setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnManageScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageScheduleActionPerformed
        ManageTimetable timetable = new ManageTimetable();
        timetable.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManageScheduleActionPerformed

    private void btnManageClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClassActionPerformed
        ManageClassWithSubject m = new ManageClassWithSubject();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManageClassActionPerformed

    private void btnManageStudentScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentScoreActionPerformed
        ManageStudentScore m = new ManageStudentScore();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManageStudentScoreActionPerformed

    private void btnReexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReexamActionPerformed
        CreateReExamination c = new   CreateReExamination();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReexamActionPerformed

    private void btnListReexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListReexamActionPerformed
        ListReexam l = new ListReexam();
        l.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnListReexamActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        ChangePassword c = new ChangePassword();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         this.setVisible(false);
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnListReexam;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageClass;
    private javax.swing.JButton btnManageSchedule;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnManageStudentScore;
    private javax.swing.JButton btnReexam;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
