/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import com.entity.StudentRequestEntity;
import com.pakage.dao.StudentRequestDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nhi
 */
public class ListReexam extends javax.swing.JFrame {
    
   private String[] columnNames = {"STT", "MSSV", "Ho ten", "Ma mon", "Cot diem can phuc khao", "Diem mon muon", "Ly do", "Trang thai"};
   private String request_id ="";
 
    /**
     * Creates new form ListReexam
     */
    public ListReexam() {
        initComponents();
        ListRequest();
         this.setLocationRelativeTo(null);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNoUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdated = new javax.swing.JButton();
        btnUnread = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNoUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNoUpdate.setText("Khong cap nhat");
        btnNoUpdate.setName("btnNoUpdate"); // NOI18N
        btnNoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Quay Ve");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnUpdated.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdated.setText("Da cap nhat");
        btnUpdated.setName("bt_kocn"); // NOI18N
        btnUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatedActionPerformed(evt);
            }
        });

        btnUnread.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUnread.setText("Chua xem");
        btnUnread.setToolTipText("");
        btnUnread.setName("bt_kocn"); // NOI18N
        btnUnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnreadActionPerformed(evt);
            }
        });

        jLabel1.setText("Cap nhat trang thai: ");

        label.setFont(new java.awt.Font("Montserrat", 0, 32)); // NOI18N
        label.setText("DANH SACH PHUC KHAO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNoUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUnread, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label)
                                .addGap(159, 159, 159)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNoUpdate)
                        .addComponent(btnUpdated)
                        .addComponent(btnUnread)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoUpdateActionPerformed
       StudentRequestDAO sqDAO = new StudentRequestDAO();
        if(!request_id.equals(""))
        {
            if(sqDAO.updateStatus(request_id,"Chua cap nhat diem")==true);
                {
                    JOptionPane.showMessageDialog(null, "Cap nhat don phuc khao thanh cong.");
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chua chon don phuc khao de cap nhat", "Notification", JOptionPane.WARNING_MESSAGE);
        }
              ListRequest();
    }//GEN-LAST:event_btnNoUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnBackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        request_id=model.getValueAt(i,0).toString();
  
 
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedActionPerformed
              StudentRequestDAO sqDAO = new StudentRequestDAO();
        if(!request_id.equals(""))
        {
            if(sqDAO.updateStatus(request_id,"Da cap nhat diem")==true);
                {
                    JOptionPane.showMessageDialog(null, "Cap nhat don phuc khao thanh cong.");
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chua chon don phuc khao de cap nhat", "Notification", JOptionPane.WARNING_MESSAGE);
        }
        ListRequest();
    }//GEN-LAST:event_btnUpdatedActionPerformed

    private void btnUnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnreadActionPerformed
                      StudentRequestDAO sqDAO = new StudentRequestDAO();
        if(!request_id.equals(""))
        {
            if(sqDAO.updateStatus(request_id,"Chua xem")==true);
                {
                    JOptionPane.showMessageDialog(null, "Cap nhat don phuc khao thanh cong.");
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Chua chon don phuc khao de cap nhat", "Notification", JOptionPane.WARNING_MESSAGE);
        }
        ListRequest();
    }//GEN-LAST:event_btnUnreadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListReexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListReexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListReexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListReexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListReexam().setVisible(true);
            }
        });
    }
    //private String[] columnNames = {"STT", "MSSV", "Ho ten", "Ma mon", "Cot diem can phuc khao", "Diem mon muon", "Ly do", "Trang thai"};
    private void ListRequest()
    {
       
        StudentRequestDAO sqDAO = new StudentRequestDAO();
        List<StudentRequestEntity> list = sqDAO.listAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        if(list.size()>0)
        {
            for (StudentRequestEntity sq: list){
                String[] rows = new String[8];
                rows[0] = String.valueOf(sq.getRequestId());
                rows[1] = sq.getStudentId();
                rows[2] = sq.getName();
                rows[3] = sq.getSubjectId();
                rows[4]=sq.getScoreName();
                rows[5]=String.valueOf(sq.getScore());
                rows[6]=sq.getReason();
                rows[7]=sq.getStatus();
                tableModel.addRow(rows);
          
            }
            jTable1.setModel(tableModel);
        }
       
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNoUpdate;
    private javax.swing.JButton btnUnread;
    private javax.swing.JButton btnUpdated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
