/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import com.entity.ClassWithSubjectEntity;
import com.entity.StudentEntity;
import com.pakage.dao.ClassWithSubjectDAO;
import com.pakage.dao.StudentDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nhi
 */
public class ManageClassWithSubject extends javax.swing.JFrame {

    /**
     * Creates new form ManageClassWithSubject
     */
    static String class_id = "";
    static String student_id="";
 
    private String[] columnNames = {
        "STT", "Ma so sinh vien", "Ho ten", "Gioi Tinh", "CMND"
    };

    public ManageClassWithSubject() {
        initComponents();
        initLayout();
    }

    private void initLayout() {
        ClassWithSubjectDAO classDAO = new ClassWithSubjectDAO();
        List<String> list = classDAO.getListClass();
        if (list.size() > 0) {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            for (String l : list) {

                comboboxModel.addElement(l);
            }
            cbxClassWithSubject.setModel(comboboxModel);
        } else {
            cbxClassWithSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbClass = new javax.swing.JLabel();
        cbxClassWithSubject = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lbStudentScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbClass.setText("Lop Mon");

        cbxClassWithSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxClassWithSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lop" }));
        cbxClassWithSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClassWithSubjectActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Them sinh vien");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setText("Xoa Sinh Vien");
        btnRemove.setName("btnRemove"); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnBack.setText("Quay ve");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbStudentScore.setFont(new java.awt.Font("Montserrat", 0, 32)); // NOI18N
        lbStudentScore.setText("Quan Ly Lop Mon Hoc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbStudentScore)
                        .addGap(111, 111, 111)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbClass)
                        .addGap(18, 18, 18)
                        .addComponent(cbxClassWithSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbStudentScore)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClass)
                    .addComponent(cbxClassWithSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClassWithSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClassWithSubjectActionPerformed
        // TODO add your handling code here:
         class_id = (String) cbxClassWithSubject.getSelectedItem();
        if (!class_id.equals("null")) {
            listStudentInClass(class_id);
        } else {
            JOptionPane.showMessageDialog(null, "Khong co lop.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cbxClassWithSubjectActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(!class_id.equals(""))
        {
            AddStudent_ClassWithSubject c = new  AddStudent_ClassWithSubject();
            c.setVisible(true);
            this.setVisible(false);
        }
    
        else
        {
            JOptionPane.showMessageDialog(null, "Chua chon lop.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
//        if(!class_id.equals(""))
//        {
//            DeleteStudent_ClassWithSubject c = new  DeleteStudent_ClassWithSubject();
//            c.setVisible(true);
//            this.setVisible(false);
             if(student_id.equals(""))
        { 
            JOptionPane.showMessageDialog(null, "Chua chon sinh vien.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
             else
             {
            ClassWithSubjectDAO classDAO = new ClassWithSubjectDAO();

        if (classDAO.deleteStudent(class_id,student_id) == true ) {
            JOptionPane.showMessageDialog(null, "Thanh cong", "Xoa sinh vien thanh cong !", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "That bai", "Xoa sinh vien that bai !", JOptionPane.INFORMATION_MESSAGE);
        }  
        
        listStudentInClass(class_id);
             }
            
//        }
//    
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Chua chon lop.", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        student_id=model.getValueAt(i,1).toString();
       
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    private void listStudentInClass(String class_id) {
        int stt = 1;
        ClassWithSubjectDAO classDAO = new ClassWithSubjectDAO();
        StudentDAO studentDAO = new StudentDAO();
        List<ClassWithSubjectEntity> list = classDAO.getList(class_id.trim());
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        for (ClassWithSubjectEntity c : list) {
            String[] rows = new String[5];
            StudentEntity s = studentDAO.get(c.getStudentId().trim());
            rows[0] = String.valueOf(stt);
            rows[1] = s.getStudentId();
            rows[2] = s.getFullName();
            rows[3] = s.getGender();
            rows[4] = s.getIdcard();
            tableModel.addRow(rows);
            stt++;

        }
        jTable1.setModel(tableModel);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageClassWithSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageClassWithSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageClassWithSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClassWithSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageClassWithSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cbxClassWithSubject;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbStudentScore;
    // End of variables declaration//GEN-END:variables
}
