/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form;

import com.entity.ClassEntity;
import com.entity.ClassWithSubjectEntity;
import com.entity.StudentEntity;
import com.entity.SubjectEntity;
import com.entity.UserEntity;
import com.pakage.dao.ClassDAO;
import com.pakage.dao.ClassWithSubjectDAO;
import com.pakage.dao.StudentDAO;
import com.pakage.dao.SubjectDAO;
import com.pakage.dao.UserDAO;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhi
 */
public class ManageTimetable extends javax.swing.JFrame {

    /**
     * Creates new form ManageSchedule
     */
    private String[] columnNames = {
        "STT", "Ma Lop", "Ma Mon", "Ten Mon", "Phong"
    };
    public ManageTimetable() {
        initComponents();
        initLayout();
         this.setLocationRelativeTo(null);
    }

    private void initLayout() {
        ClassDAO classDAO = new ClassDAO();
        List<ClassEntity> list = classDAO.listAll();
        if (list.size() > 0) {
            DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
            for (ClassEntity l : list) {
                ClassEntity _l = ClassDAO.find(l.getClassId());
                comboboxModel.addElement(l.getClassId());
            }
            cbxClass.setModel(comboboxModel);
        } else {
            cbxClass.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStudentScore = new javax.swing.JLabel();
        btnImport = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxClass = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label = new javax.swing.JLabel();

        lbStudentScore.setFont(new java.awt.Font("Montserrat", 0, 32)); // NOI18N
        lbStudentScore.setText("Quan ly sinh vien");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnImport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImport.setText("Import TKB");
        btnImport.setName("btnImport"); // NOI18N
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lop");

        cbxClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClassActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Quay Ve");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        label.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        label.setText("Thoi khoa bieu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cbxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnBack)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack))
                    .addComponent(btnImport))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        JFileChooser file_chooser = new JFileChooser();

        int result = file_chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file_chooser.getSelectedFile();
            importFromFile(selectedFile);

        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void cbxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClassActionPerformed
        // TODO add your handling code here:
        String class_id = (String) cbxClass.getSelectedItem();
        if (!class_id.equals("null")) {
            xemtkb(class_id);
        } else {
            JOptionPane.showMessageDialog(null, "Ch?a có th?i khóa bi?u.", "Notification", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cbxClassActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTimetable().setVisible(true);
            }
        });
    }

    private void importFromFile(File selectedFile) {
        String csvFile = selectedFile.toString();
        String cvsSplitBy = ",";
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(csvFile));
            String line = "";
            int d = 0;
            String mamonnoinsert = "";
            SubjectDAO subjectDAO = new  SubjectDAO();
            ClassWithSubjectDAO classDAO = new ClassWithSubjectDAO();
            StudentDAO studentDAO = new StudentDAO();
            //Danh sach lop mon moi
           
            try {
                if ((line = br.readLine()) != null) {
                    String[] l = line.split(cvsSplitBy);
                    String class_id=l[0];
                        while ((line = br.readLine()) != null) {
                            String[] sbj = line.split(cvsSplitBy);
                            SubjectEntity new_subject = new  SubjectEntity(sbj[0], class_id, sbj[1], sbj[2]);
                            String class_with_subject_id = class_id + "-"+ sbj[0];
                            System.out.println("ten lop: "+class_with_subject_id);
                            List<StudentEntity> liststd= studentDAO.getListStudent(class_id);
                            for (StudentEntity s :liststd)
                            {
                                System.out.println("sv: "+s.getStudentId());
                            ClassWithSubjectEntity new_class = new ClassWithSubjectEntity(class_with_subject_id,s.getStudentId());
                            classDAO.create(new_class);
                            }
                            //Them danh sach lop mon moi 
                            // if (SubjectDAO.create(new_subject) == true && ClassWithSubjectDAO.create(new_class) == true)
                            if (subjectDAO.create(new_subject) == true ) {
                                d++;
                            } else {
                                mamonnoinsert = sbj[0] + ",";
                            }
                        }
                    
                }
                JOptionPane.showMessageDialog(this, "Da insert " + d + " mon.\n Mamon chua insert:" + mamonnoinsert);
            } catch (IOException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        initLayout();
    }
    
       private void xemtkb(String class_id) {
        int stt = 1;
        SubjectDAO subjectDAO = new SubjectDAO();
        List<SubjectEntity> list = subjectDAO.findByClassId(class_id);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        for (SubjectEntity s : list) {
            String[] rows = new String[5];
            rows[0] = String.valueOf(stt);
            rows[1] = s.getSubjectId();
            rows[2] = s.getClassId();
            rows[3] = s.getSubjectName();
            rows[4] = s.getRoom();
            tableModel.addRow(rows);
            stt++;
        }
        jTable1.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox cbxClass;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbStudentScore;
    // End of variables declaration//GEN-END:variables
}
